
package au.com.unico.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GCDServiceService", targetNamespace = "http://webservice.unico.com.au/", wsdlLocation = "http://localhost:8088/WebServiceProject/GCDService?wsdl")
public class GCDServiceService
    extends Service
{

    private final static URL GCDSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException GCDSERVICESERVICE_EXCEPTION;
    private final static QName GCDSERVICESERVICE_QNAME = new QName("http://webservice.unico.com.au/", "GCDServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/WebServiceProject/GCDService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GCDSERVICESERVICE_WSDL_LOCATION = url;
        GCDSERVICESERVICE_EXCEPTION = e;
    }

    public GCDServiceService() {
        super(__getWsdlLocation(), GCDSERVICESERVICE_QNAME);
    }

    public GCDServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GCDSERVICESERVICE_QNAME, features);
    }

    public GCDServiceService(URL wsdlLocation) {
        super(wsdlLocation, GCDSERVICESERVICE_QNAME);
    }

    public GCDServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GCDSERVICESERVICE_QNAME, features);
    }

    public GCDServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GCDServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GCDService
     */
    @WebEndpoint(name = "GCDServicePort")
    public GCDService getGCDServicePort() {
        return super.getPort(new QName("http://webservice.unico.com.au/", "GCDServicePort"), GCDService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GCDService
     */
    @WebEndpoint(name = "GCDServicePort")
    public GCDService getGCDServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.unico.com.au/", "GCDServicePort"), GCDService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GCDSERVICESERVICE_EXCEPTION!= null) {
            throw GCDSERVICESERVICE_EXCEPTION;
        }
        return GCDSERVICESERVICE_WSDL_LOCATION;
    }

}
