
package au.com.unico.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GCDService", targetNamespace = "http://webservice.unico.com.au/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GCDService {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "gcdList", targetNamespace = "http://webservice.unico.com.au/", className = "au.com.unico.webservice.GcdList")
    @ResponseWrapper(localName = "gcdListResponse", targetNamespace = "http://webservice.unico.com.au/", className = "au.com.unico.webservice.GcdListResponse")
    public List<Integer> gcdList();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "gcd", targetNamespace = "http://webservice.unico.com.au/", className = "au.com.unico.webservice.Gcd")
    @ResponseWrapper(localName = "gcdResponse", targetNamespace = "http://webservice.unico.com.au/", className = "au.com.unico.webservice.GcdResponse")
    public int gcd();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "gcdSum", targetNamespace = "http://webservice.unico.com.au/", className = "au.com.unico.webservice.GcdSum")
    @ResponseWrapper(localName = "gcdSumResponse", targetNamespace = "http://webservice.unico.com.au/", className = "au.com.unico.webservice.GcdSumResponse")
    public int gcdSum();

}
